# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App

on:
  push:
    branches:
      - main
    paths:
      - "Server/**"
      - "!Server/**.md"
      - "!Server/.*"
      - "!**/.gitignore"
      - "!**/README.md"
      - "!**/CONTRIBUTING.md"

  pull_request:
    branches:
      - main
    paths:
      - "Server/**"
      - "!Server/**.md"
      - "!Server/.*"
      - "!**/.gitignore"
      - "!**/README.md"
      - "!**/CONTRIBUTING.md"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: npm install and build
        run: |
          cd Server
          npm install
          npm run build --if-present

      - name: Prepare deployment package
        run: |
          mkdir -p artifact
          cp -r Server/* artifact/
          cp Server/package*.json artifact/
          cp Server/.env artifact/ || true
          cp Server/web.config artifact/ || true

      - name: Zip artifact
        run: |
          cd artifact
          zip -r ../release.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: |
          mkdir -p extracted
          unzip release.zip -d extracted

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_52F7FD40005E4C5B937881C0D26E159E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_384137FBAA0348B38873E63D1659A136 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6DE73D93CFC0471287859CBA44E73F1A }}

      - name: Deploy to Azure
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "gavel-club"
          slot-name: "Production"
          package: extracted
